In [19]:
import pickle
import pandas as pd

# file = "knn_times_evis.pkl" # data reported in eurovis submission
file = "./rn_times.pkl"
knn_times = {}
with open(file, "rb") as f:
    knn_times = pickle.load(f)

In [20]:
keys_with_multiple = [k for k, v in knn_times.items() if len(v) > 1]

In [9]:
print(file)
data = []

for k in keys_with_multiple:
    n, d = k
    times = knn_times[k]
    mean = sum(times) / len(times)
    max_dev = max(abs(mean - x) for x in times)
    std_dev = sum(abs(mean - x) for x in times) / (len(times) + 1)
    
    data.append({"Data Points": n, "Dimension": d, "Mean Time (s)": mean, "Max Deviation (s)": max_dev, "Std. Deviation (s)": std_dev})

df = pd.DataFrame(data)
df

./knn_times_15.pkl

,Data Points,Dimension,Mean Time (s),Max Deviation (s),Std. Deviation (s)
0,60000,1024,209.658332,194.030877,29.548710
1,60000,512,97.374567,84.644599,17.700382

In [12]:
print(file)
data = []

for k in keys_with_multiple:
    n, d = k
    times = knn_times[k]
    mean = sum(times) / len(times)
    max_dev = max(abs(mean - x) for x in times)
    std_dev = sum(abs(mean - x) for x in times) / (len(times) + 1)
    
    data.append({"Data Points": n, "Dimension": d, "Mean Time (s)": mean, "Max Deviation (s)": max_dev, "Std. Deviation (s)": std_dev})

df = pd.DataFrame(data)
df

./knn_times_20.pkl

,Data Points,Dimension,Mean Time (s),Max Deviation (s),Std. Deviation (s)
0,60000,1024,208.439449,185.574897,27.067624
1,60000,512,99.647700,80.645380,15.665989

In [15]:
print(file)
data = []

for k in keys_with_multiple:
    n, d = k
    times = knn_times[k]
    mean = sum(times) / len(times)
    max_dev = max(abs(mean - x) for x in times)
    std_dev = sum(abs(mean - x) for x in times) / (len(times) + 1)
    
    data.append({"Data Points": n, "Dimension": d, "Mean Time (s)": mean, "Max Deviation (s)": max_dev, "Std. Deviation (s)": std_dev})

df = pd.DataFrame(data)
df

./knn_times_25.pkl

,Data Points,Dimension,Mean Time (s),Max Deviation (s),Std. Deviation (s)
0,60000,1024,207.124097,174.542001,26.639385
1,60000,512,98.632165,74.410294,15.310537

In [18]:
print(file)
data = []

for k in keys_with_multiple:
    n, d = k
    times = knn_times[k]
    mean = sum(times) / len(times)
    max_dev = max(abs(mean - x) for x in times)
    std_dev = sum(abs(mean - x) for x in times) / (len(times) + 1)
    
    data.append({"Data Points": n, "Dimension": d, "Mean Time (s)": mean, "Max Deviation (s)": max_dev, "Std. Deviation (s)": std_dev})

df = pd.DataFrame(data)
df

./knn_times_evis.pkl

,Data Points,Dimension,Mean Time (s),Max Deviation (s),Std. Deviation (s)
0,50000,1024,17.044676,2.113131,1.408754
1,50000,4096,51.694072,0.595320,0.396880
2,60000,1024,19.185684,2.343185,1.543820
3,60000,512,13.561726,0.147304,0.098202
4,60000,4096,77.315284,4.931104,1.972442
5,60000,8192,98.931575,7.953036,5.302024
6,60000,2048,27.999866,1.707123,1.138082
7,60000,16384,191.439057,18.047902,12.031934
8,10000,1024,2.473663,0.030579,0.017040
9,10000,512,2.398657,0.120382,0.080254
10,10000,4096,3.888811,0.187491,0.074996
11,10000,8192,5.177944,0.210415,0.140276
12,10000,2048,2.810567,0.084711,0.056474
13,10000,16384,8.589189,0.600445,0.400297
14,70000,1024,28.210142,1.398042,0.932028
15,70000,4096,100.488591,1.645658,1.097105

In [21]:
print(file)
data = []

for k in keys_with_multiple:
    n, d = k
    times = knn_times[k]
    mean = sum(times) / len(times)
    max_dev = max(abs(mean - x) for x in times)
    std_dev = sum(abs(mean - x) for x in times) / (len(times) + 1)
    
    data.append({"Data Points": n, "Dimension": d, "Mean Time (s)": mean, "Max Deviation (s)": max_dev, "Std. Deviation (s)": std_dev})

df = pd.DataFrame(data)
df

./rn_times.pkl

,Data Points,Dimension,Mean Time (s),Max Deviation (s),Std. Deviation (s)
0,50000,1024,86.244585,54.587530,10.381505
1,10000,1024,9.762574,5.605422,1.259317
2,60000,1024,108.918219,71.693268,12.845063
3,50000,512,52.654474,37.071368,5.241996
4,10000,512,4.620659,2.355412,0.484221
5,60000,512,68.209919,47.275293,6.589842

In [5]:
df2 = df.drop(columns=["Max Deviation (s)"]).sort_values(by=["Data Points", "Dimension"])
df2 = df2[(df2["Data Points"] == 10000) | (df2["Data Points"] == 60000)]

In [6]:
print(df2.to_latex(index=False, ))

KeyboardInterrupt: